name: CI

on:
  push:
    branches:
      - '**'  # Run on all branches

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements/dev.txt

      - name: Run migrations
        run: |
          source venv/bin/activate
          python3 manage.py migrate

      - name: Run linter
        run: |
          source venv/bin/activate
          flake8 . && echo "Linting passed"

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest
